import React, { useEffect, useMemo, useState } from "react";
import {
  Bar,
  BarChart,
  CartesianGrid,
  Line,
  LineChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";

import Badge from "../components/Badge";
import EmptyState from "../components/EmptyState";
import { BotIcon, ClockIcon, MailIcon, SparklesIcon, UserPlusIcon } from "../components/Icons";
import Skeleton from "../components/Skeleton";
import StatCard from "../components/StatCard";
import { getDashboardSummary } from "../services/api";

const Dashboard = () => {
  const [summary, setSummary] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [lastUpdated, setLastUpdated] = useState(null);

  useEffect(() => {
    const loadSummary = async () => {
      try {
        const data = await getDashboardSummary();
        setSummary(data);
        setLastUpdated(new Date());
      } catch (err) {
        setError("Unable to load dashboard summary.");
      } finally {
        setLoading(false);
      }
    };
    loadSummary();
  }, []);

  const leadTrendData = useMemo(() => {
    if (!summary?.charts?.lead_trend) {
      return [];
    }
    return summary.charts.lead_trend.map((point) => ({
      day: new Date(point.date).toLocaleDateString(undefined, { weekday: "short" }),
      leads: point.count,
    }));
  }, [summary]);

  const emailCategoryData = useMemo(() => {
    if (!summary?.charts?.email_category_breakdown) {
      return [];
    }
    return summary.charts.email_category_breakdown.map((item) => ({
      category: item.category,
      count: item.count,
    }));
  }, [summary]);

  const statusFunnel = useMemo(
    () => summary?.charts?.lead_status_funnel || [],
    [summary]
  );

  const recentActivity = useMemo(
    () => summary?.recent_activity?.slice(0, 10) || [],
    [summary]
  );

  return (
    <div className="space-y-8">
      <div className="flex flex-wrap items-center justify-between gap-4">
        <div>
          <h2 className="text-2xl font-semibold text-slate-900 dark:text-white">
            Revenue command center
          </h2>
          <p className="text-sm text-slate-500 dark:text-slate-400">
            Live view of lead flow, inbox automation, and AI coverage.
          </p>
        </div>
        <div className="flex items-center gap-2 rounded-full border border-slate-200 bg-white px-4 py-2 text-xs text-slate-500 shadow-sm dark:border-slate-800 dark:bg-slate-900 dark:text-slate-300">
          <ClockIcon className="h-4 w-4" />
          {lastUpdated
            ? `Updated ${lastUpdated.toLocaleTimeString([], {
                hour: "2-digit",
                minute: "2-digit",
              })}`
            : "Syncing data"}
        </div>
      </div>

      {loading ? (
        <div className="grid gap-6 md:grid-cols-2 xl:grid-cols-4">
          {Array.from({ length: 4 }).map((_, index) => (
            <Skeleton key={`metric-${index}`} className="h-32" />
          ))}
        </div>
      ) : error ? (
        <EmptyState
          title="Unable to load metrics"
          description={error}
          icon={<SparklesIcon className="h-6 w-6" />}
        />
      ) : (
        <div className="grid gap-6 md:grid-cols-2 xl:grid-cols-4">
          <StatCard
            label="New Leads Today"
            value={summary?.kpis?.leads_today || 0}
            icon={<UserPlusIcon className="h-5 w-5" />}
            helper="High intent contacts"
            trend={`${summary?.kpis?.total_leads || 0} total`}
          />
          <StatCard
            label="Emails Processed"
            value={summary?.kpis?.emails_processed || 0}
            icon={<MailIcon className="h-5 w-5" />}
            helper="Last 24 hours"
            trend={`${summary?.kpis?.emails_processed_30d || 0} in 30 days`}
          />
          <StatCard
            label="AI Replies Sent"
            value={summary?.kpis?.ai_replies_sent || 0}
            icon={<BotIcon className="h-5 w-5" />}
            helper="Generated by AI"
            trend={`${summary?.kpis?.ai_replies_sent_30d || 0} auto`}
          />
          <StatCard
            label="Pending Actions"
            value={summary?.kpis?.pending_actions || 0}
            icon={<ClockIcon className="h-5 w-5" />}
            helper="Awaiting review"
          />
        </div>
      )}

      <div className="grid gap-6 lg:grid-cols-[2fr_1fr]">
        <div className="rounded-2xl border border-slate-100 bg-white p-6 shadow-md dark:border-slate-800 dark:bg-slate-900/80">
          <div className="flex items-center justify-between">
            <div>
              <h3 className="text-sm font-semibold text-slate-900 dark:text-white">
                Leads over time
              </h3>
              <p className="text-xs text-slate-500 dark:text-slate-400">
                New lead volume over the last 7 days
              </p>
            </div>
            <span className="text-xs text-emerald-600 dark:text-emerald-300">
              {summary?.kpis?.leads_generated_30d || 0} leads in 30 days
            </span>
          </div>
          <div className="mt-6 h-64">
            {loading ? (
              <Skeleton className="h-64" />
            ) : leadTrendData.length ? (
              <ResponsiveContainer width="100%" height="100%">
                <LineChart data={leadTrendData}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" />
                  <XAxis dataKey="day" tick={{ fill: "#94a3b8", fontSize: 12 }} />
                  <YAxis tick={{ fill: "#94a3b8", fontSize: 12 }} />
                  <Tooltip
                    contentStyle={{
                      borderRadius: 12,
                      borderColor: "#e2e8f0",
                      fontSize: 12,
                    }}
                  />
                  <Line
                    type="monotone"
                    dataKey="leads"
                    stroke="#4f46e5"
                    strokeWidth={3}
                    dot={{ fill: "#4f46e5", r: 3 }}
                  />
                </LineChart>
              </ResponsiveContainer>
            ) : (
              <EmptyState
                title="No lead activity"
                description="Leads will appear once inbound traffic starts."
                icon={<UserPlusIcon className="h-6 w-6" />}
              />
            )}
          </div>
        </div>
        <div className="rounded-2xl border border-slate-100 bg-white p-6 shadow-md dark:border-slate-800 dark:bg-slate-900/80">
          <div>
            <h3 className="text-sm font-semibold text-slate-900 dark:text-white">
              Emails by category
            </h3>
            <p className="text-xs text-slate-500 dark:text-slate-400">
              Distribution of inbound conversations
            </p>
          </div>
          <div className="mt-6 h-64">
            {loading ? (
              <Skeleton className="h-64" />
            ) : emailCategoryData.length ? (
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={emailCategoryData}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" />
                  <XAxis dataKey="category" tick={{ fill: "#94a3b8", fontSize: 12 }} />
                  <YAxis tick={{ fill: "#94a3b8", fontSize: 12 }} />
                  <Tooltip
                    contentStyle={{
                      borderRadius: 12,
                      borderColor: "#e2e8f0",
                      fontSize: 12,
                    }}
                  />
                  <Bar dataKey="count" fill="#60a5fa" radius={[8, 8, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            ) : (
              <EmptyState
                title="No emails yet"
                description="Once an inbox is connected, categories will populate here."
                icon={<MailIcon className="h-6 w-6" />}
              />
            )}
          </div>
        </div>
      </div>

      <div className="grid gap-6 lg:grid-cols-[1.15fr_1fr]">
        <div className="rounded-2xl border border-slate-100 bg-white p-6 shadow-md dark:border-slate-800 dark:bg-slate-900/80">
          <div className="flex items-center justify-between">
            <div>
              <h3 className="text-sm font-semibold text-slate-900 dark:text-white">
                Lead status funnel
              </h3>
              <p className="text-xs text-slate-500 dark:text-slate-400">
                Pipeline distribution across active stages
              </p>
            </div>
            <Badge variant="info">Pipeline health</Badge>
          </div>
          <div className="mt-6 space-y-4">
            {loading ? (
              <div className="space-y-3">
                {Array.from({ length: 4 }).map((_, index) => (
                  <Skeleton key={`funnel-${index}`} className="h-10" />
                ))}
              </div>
            ) : statusFunnel.length ? (
              statusFunnel.map((stage, index) => (
                <div key={`${stage.status}-${index}`} className="space-y-2">
                  <div className="flex items-center justify-between text-sm text-slate-600 dark:text-slate-300">
                    <span className="capitalize">{stage.status.replace("_", " ")}</span>
                    <span className="font-semibold text-slate-900 dark:text-white">
                      {stage.count}
                    </span>
                  </div>
                  <div className="h-2 rounded-full bg-slate-100 dark:bg-slate-800">
                    <div
                      className="h-2 rounded-full bg-gradient-to-r from-indigo-500 to-sky-400"
                      style={{
                        width: `${Math.max(stage.percentage || 0, 6)}%`,
                      }}
                    />
                  </div>
                </div>
              ))
            ) : (
              <EmptyState
                title="No pipeline data"
                description="Lead stages will appear as you classify inbound requests."
                icon={<SparklesIcon className="h-6 w-6" />}
              />
            )}
          </div>
        </div>
        <div className="rounded-2xl border border-slate-100 bg-white p-6 shadow-md dark:border-slate-800 dark:bg-slate-900/80">
          <div className="flex items-center justify-between">
            <div>
              <h3 className="text-sm font-semibold text-slate-900 dark:text-white">
                Recent activity
              </h3>
              <p className="text-xs text-slate-500 dark:text-slate-400">
                Latest 10 system events
              </p>
            </div>
            <span className="text-xs text-slate-400 dark:text-slate-500">
              {recentActivity.length} events
            </span>
          </div>
          {loading ? (
            <div className="mt-6 space-y-3">
              {Array.from({ length: 5 }).map((_, index) => (
                <Skeleton key={`recent-${index}`} className="h-12" />
              ))}
            </div>
          ) : recentActivity.length ? (
            <div className="mt-6 space-y-4">
              {recentActivity.map((entry, index) => (
                <div key={entry.id} className="flex gap-3">
                  <div className="flex flex-col items-center">
                    <span className="h-2.5 w-2.5 rounded-full bg-indigo-500" />
                    {index !== recentActivity.length - 1 ? (
                      <span className="mt-1 h-full w-px bg-slate-200 dark:bg-slate-700" />
                    ) : null}
                  </div>
                  <div className="space-y-1">
                    <p className="text-sm font-medium text-slate-900 dark:text-white">
                      {entry.title}
                    </p>
                    <p className="text-xs text-slate-500 dark:text-slate-400">
                      {entry.detail || "No additional details"}
                    </p>
                    <p className="text-xs text-slate-400 dark:text-slate-500">
                      {new Date(entry.created_at).toLocaleString()}
                    </p>
                  </div>
                </div>
              ))}
            </div>
          ) : (
            <div className="mt-6">
              <EmptyState
                title="No events yet"
                description="New activity will appear as the team engages leads."
                icon={<SparklesIcon className="h-6 w-6" />}
              />
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default Dashboard;
