import React, { useEffect, useMemo, useState } from "react";
import {
  Bar,
  BarChart,
  CartesianGrid,
  Line,
  LineChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";

import EmptyState from "../components/EmptyState";
import { BotIcon, ClockIcon, MailIcon, SparklesIcon, UserPlusIcon } from "../components/Icons";
import Skeleton from "../components/Skeleton";
import StatCard from "../components/StatCard";
import { getAnalyticsOverview, getDashboardActivity, getDashboardStats } from "../services/api";

const Dashboard = () => {
  const [stats, setStats] = useState({
    total_leads: 0,
    leads_today: 0,
    emails_today: 0,
    replies_sent: 0,
  });
  const [overview, setOverview] = useState(null);
  const [activity, setActivity] = useState([]);
  const [loading, setLoading] = useState(true);
  const [overviewLoading, setOverviewLoading] = useState(true);
  const [activityLoading, setActivityLoading] = useState(true);
  const [error, setError] = useState("");
  const [lastUpdated, setLastUpdated] = useState(null);

  useEffect(() => {
    const loadStats = async () => {
      try {
        const data = await getDashboardStats();
        setStats(data);
        setLastUpdated(new Date());
      } catch (err) {
        setError("Unable to load dashboard metrics.");
      } finally {
        setLoading(false);
      }
    };
    loadStats();
  }, []);

  useEffect(() => {
    const loadOverview = async () => {
      try {
        const data = await getAnalyticsOverview();
        setOverview(data);
      } catch (err) {
        // handled by empty states
      } finally {
        setOverviewLoading(false);
      }
    };
    loadOverview();
  }, []);

  useEffect(() => {
    const loadActivity = async () => {
      try {
        const data = await getDashboardActivity();
        setActivity(data.recent_activity || []);
      } catch (err) {
        setActivity([]);
      } finally {
        setActivityLoading(false);
      }
    };
    loadActivity();
  }, []);

  const leadTrendData = useMemo(() => {
    if (!overview?.lead_trend) {
      return [];
    }
    return overview.lead_trend.map((point) => ({
      day: new Date(point.date).toLocaleDateString(undefined, { weekday: "short" }),
      leads: point.count,
    }));
  }, [overview]);

  const emailCategoryData = useMemo(() => {
    if (!overview?.email_category_breakdown) {
      return [];
    }
    return overview.email_category_breakdown.map((item) => ({
      category: item.category,
      count: item.count,
    }));
  }, [overview]);

  const pendingActions = useMemo(
    () => Math.max(stats.total_leads - stats.replies_sent, 0),
    [stats]
  );

  const recentActivity = useMemo(() => activity.slice(0, 10), [activity]);

  return (
    <div className="space-y-8">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-semibold text-slate-900">Dashboard</h2>
          <p className="text-sm text-slate-500">Snapshot of incoming business activity.</p>
        </div>
        <div className="hidden items-center gap-2 rounded-full border border-slate-200 bg-white px-4 py-2 text-xs text-slate-500 md:flex">
          <ClockIcon className="h-4 w-4" />
          {lastUpdated
            ? `Updated ${lastUpdated.toLocaleTimeString([], {
                hour: "2-digit",
                minute: "2-digit",
              })}`
            : "Syncing data"}
        </div>
      </div>

      {loading ? (
        <div className="grid gap-6 md:grid-cols-2 xl:grid-cols-4">
          {Array.from({ length: 4 }).map((_, index) => (
            <Skeleton key={`metric-${index}`} className="h-32" />
          ))}
        </div>
      ) : error ? (
        <EmptyState
          title="Unable to load metrics"
          description={error}
          icon={<SparklesIcon className="h-6 w-6" />}
        />
      ) : (
        <div className="grid gap-6 md:grid-cols-2 xl:grid-cols-4">
          <StatCard
            label="New Leads Today"
            value={stats.leads_today}
            icon={<UserPlusIcon className="h-5 w-5" />}
            helper="High intent contacts"
            trend={`${stats.total_leads} total`}
          />
          <StatCard
            label="Emails Processed"
            value={stats.emails_today}
            icon={<MailIcon className="h-5 w-5" />}
            helper="Last 24 hours"
            trend={`${overview?.emails_processed || 0} in 30 days`}
          />
          <StatCard
            label="AI Replies Sent"
            value={stats.replies_sent}
            icon={<BotIcon className="h-5 w-5" />}
            helper="Generated by AI"
            trend={`${overview?.emails_auto_replied || 0} auto`}
          />
          <StatCard
            label="Pending Actions"
            value={pendingActions}
            icon={<ClockIcon className="h-5 w-5" />}
            helper="Awaiting review"
          />
        </div>
      )}

      <div className="grid gap-6 lg:grid-cols-[2fr_1fr]">
        <div className="rounded-2xl border border-slate-100 bg-white p-6 shadow-md">
          <div className="flex items-center justify-between">
            <div>
              <h3 className="text-sm font-semibold text-slate-900">Leads per day</h3>
              <p className="text-xs text-slate-500">Last 7 days conversion funnel</p>
            </div>
            <span className="text-xs text-emerald-600">
              {overview?.leads_generated || 0} leads in 30 days
            </span>
          </div>
          <div className="mt-6 h-64">
            {overviewLoading ? (
              <Skeleton className="h-64" />
            ) : leadTrendData.length ? (
              <ResponsiveContainer width="100%" height="100%">
                <LineChart data={leadTrendData}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" />
                  <XAxis dataKey="day" tick={{ fill: "#94a3b8", fontSize: 12 }} />
                  <YAxis tick={{ fill: "#94a3b8", fontSize: 12 }} />
                  <Tooltip
                    contentStyle={{
                      borderRadius: 12,
                      borderColor: "#e2e8f0",
                      fontSize: 12,
                    }}
                  />
                  <Line
                    type="monotone"
                    dataKey="leads"
                    stroke="#4f46e5"
                    strokeWidth={3}
                    dot={{ fill: "#4f46e5", r: 3 }}
                  />
                </LineChart>
              </ResponsiveContainer>
            ) : (
              <EmptyState
                title="No lead activity"
                description="Leads will appear once inbound traffic starts."
                icon={<UserPlusIcon className="h-6 w-6" />}
              />
            )}
          </div>
        </div>
        <div className="rounded-2xl border border-slate-100 bg-white p-6 shadow-md">
          <div>
            <h3 className="text-sm font-semibold text-slate-900">Emails by category</h3>
            <p className="text-xs text-slate-500">Distribution of inbound conversations</p>
          </div>
          <div className="mt-6 h-64">
            {overviewLoading ? (
              <Skeleton className="h-64" />
            ) : emailCategoryData.length ? (
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={emailCategoryData}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" />
                  <XAxis dataKey="category" tick={{ fill: "#94a3b8", fontSize: 12 }} />
                  <YAxis tick={{ fill: "#94a3b8", fontSize: 12 }} />
                  <Tooltip
                    contentStyle={{
                      borderRadius: 12,
                      borderColor: "#e2e8f0",
                      fontSize: 12,
                    }}
                  />
                  <Bar dataKey="count" fill="#60a5fa" radius={[8, 8, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            ) : (
              <EmptyState
                title="No emails yet"
                description="Once an inbox is connected, categories will populate here."
                icon={<MailIcon className="h-6 w-6" />}
              />
            )}
          </div>
        </div>
      </div>

      <div className="rounded-2xl border border-slate-100 bg-white p-6 shadow-md">
        <div className="flex items-center justify-between">
          <div>
            <h3 className="text-sm font-semibold text-slate-900">Recent activity</h3>
            <p className="text-xs text-slate-500">Latest 10 system events</p>
          </div>
          <span className="text-xs text-slate-400">
            {recentActivity.length} events
          </span>
        </div>
        {activityLoading ? (
          <div className="mt-6 space-y-3">
            {Array.from({ length: 5 }).map((_, index) => (
              <Skeleton key={`recent-${index}`} className="h-12" />
            ))}
          </div>
        ) : recentActivity.length ? (
          <div className="mt-6 overflow-hidden rounded-xl border border-slate-100">
            <table className="min-w-full text-sm">
              <thead className="bg-slate-50 text-slate-500">
                <tr>
                  <th className="text-left px-4 py-3 font-medium">Event</th>
                  <th className="text-left px-4 py-3 font-medium">Details</th>
                  <th className="text-left px-4 py-3 font-medium">Time</th>
                </tr>
              </thead>
              <tbody>
                {recentActivity.map((entry) => (
                  <tr key={entry.id} className="border-t border-slate-100">
                    <td className="px-4 py-3 font-medium text-slate-900">{entry.title}</td>
                    <td className="px-4 py-3 text-slate-600">{entry.detail || "-"}</td>
                    <td className="px-4 py-3 text-slate-500">
                      {new Date(entry.created_at).toLocaleString()}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        ) : (
          <div className="mt-6">
            <EmptyState
              title="No events yet"
              description="New activity will appear as the team engages leads."
              icon={<SparklesIcon className="h-6 w-6" />}
            />
          </div>
        )}
      </div>
    </div>
  );
};

export default Dashboard;
