import React, { useMemo } from "react";
import { Link } from "react-router-dom";
import {
  Bar,
  BarChart,
  CartesianGrid,
  Line,
  LineChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";

import Badge from "../components/Badge";
import StatCard from "../components/StatCard";
import StatusBadge from "../components/StatusBadge";
import {
  BotIcon,
  ClockIcon,
  MailIcon,
  MoonIcon,
  SparklesIcon,
  SunIcon,
  UserPlusIcon,
} from "../components/Icons";
import { useTheme } from "../context/ThemeContext";
import { demoActivities, demoEmails, demoLeads, demoSummary } from "../data/demoData";

const Demo = () => {
  const { theme, toggleTheme } = useTheme();
  const maxStatusValue = useMemo(
    () => Math.max(...demoSummary.status_funnel.map((item) => item.value)),
    []
  );

  return (
    <div
      className={`min-h-screen bg-[var(--bg-app)] text-slate-900 dark:text-slate-100 app-shell ${
        theme === "dark" ? "dark-shell" : ""
      }`}
    >
      <header className="sticky top-0 z-40 border-b border-slate-200 bg-white/80 backdrop-blur dark:border-slate-800 dark:bg-slate-950/80">
        <div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-4">
          <div className="flex items-center gap-3">
            <span className="flex h-10 w-10 items-center justify-center rounded-2xl bg-indigo-600 text-white shadow-lg shadow-indigo-500/30">
              <BotIcon className="h-5 w-5" />
            </span>
            <div>
              <p className="text-xs uppercase tracking-[0.3em] text-slate-400 dark:text-slate-500">
                AI Automation Portal
              </p>
              <p className="text-base font-semibold text-slate-900 dark:text-white">Demo Dashboard</p>
            </div>
          </div>
          <div className="flex items-center gap-3">
            <Link
              className="hidden rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-semibold text-slate-700 shadow-sm transition hover:bg-slate-100 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-200 dark:hover:bg-slate-800 md:inline-flex"
              to="/"
            >
              Back to home
            </Link>
            <Link
              className="rounded-xl bg-indigo-600 px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-indigo-500"
              to="/register"
            >
              Get started free
            </Link>
            <button
              type="button"
              onClick={toggleTheme}
              className="rounded-full border border-slate-200 bg-white p-2 text-slate-600 shadow-sm transition hover:bg-slate-100 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-200 dark:hover:bg-slate-800"
              aria-label="Toggle theme"
            >
              {theme === "dark" ? <SunIcon className="h-5 w-5" /> : <MoonIcon className="h-5 w-5" />}
            </button>
          </div>
        </div>
      </header>

      <main className="mx-auto flex max-w-6xl flex-col gap-8 px-6 py-8">
        <div className="rounded-2xl border border-amber-200 bg-amber-50 px-5 py-4 text-amber-800 shadow-sm dark:border-amber-500/30 dark:bg-amber-500/10 dark:text-amber-200">
          <div className="flex flex-wrap items-center justify-between gap-4">
            <div className="flex items-center gap-3">
              <Badge variant="warning">Demo mode</Badge>
              <p className="text-sm font-medium">
                Demo mode — connect your email to activate full features
              </p>
            </div>
            <Link
              className="rounded-xl bg-amber-600 px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-amber-500"
              to="/register"
            >
              Connect email
            </Link>
          </div>
        </div>

        <div className="grid gap-6 md:grid-cols-2 xl:grid-cols-4">
          <StatCard
            label="New Leads Today"
            value={demoSummary.kpis.leads_today}
            icon={<UserPlusIcon className="h-5 w-5" />}
            helper="High intent"
            trend={`${demoSummary.kpis.total_leads} total`}
          />
          <StatCard
            label="Emails Processed"
            value={demoSummary.kpis.emails_processed}
            icon={<MailIcon className="h-5 w-5" />}
            helper="Last 24 hours"
            trend={`${demoSummary.kpis.emails_processed_30d} in 30 days`}
          />
          <StatCard
            label="AI Replies Sent"
            value={demoSummary.kpis.ai_replies_sent}
            icon={<BotIcon className="h-5 w-5" />}
            helper="Generated by AI"
            trend={`${demoSummary.kpis.ai_replies_sent_30d} auto`}
          />
          <StatCard
            label="Pending Actions"
            value={demoSummary.kpis.pending_actions}
            icon={<ClockIcon className="h-5 w-5" />}
            helper="Awaiting review"
          />
        </div>

        <div className="grid gap-6 lg:grid-cols-[2fr_1fr]">
          <div className="rounded-2xl border border-slate-100 bg-white p-6 shadow-md dark:border-slate-800 dark:bg-slate-900/80">
            <div className="flex items-center justify-between">
              <div>
                <h3 className="text-sm font-semibold text-slate-900 dark:text-white">
                  Lead momentum
                </h3>
                <p className="text-xs text-slate-500 dark:text-slate-400">
                  New lead volume over the last 7 days
                </p>
              </div>
              <span className="text-xs text-emerald-600 dark:text-emerald-300">
                {demoSummary.kpis.leads_generated_30d} leads in 30 days
              </span>
            </div>
            <div className="mt-6 h-64">
              <ResponsiveContainer width="100%" height="100%">
                <LineChart data={demoSummary.lead_trend}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" />
                  <XAxis dataKey="day" tick={{ fill: "#94a3b8", fontSize: 12 }} />
                  <YAxis tick={{ fill: "#94a3b8", fontSize: 12 }} />
                  <Tooltip
                    contentStyle={{
                      borderRadius: 12,
                      borderColor: "#e2e8f0",
                      fontSize: 12,
                    }}
                  />
                  <Line
                    type="monotone"
                    dataKey="leads"
                    stroke="#4f46e5"
                    strokeWidth={3}
                    dot={{ fill: "#4f46e5", r: 3 }}
                  />
                </LineChart>
              </ResponsiveContainer>
            </div>
          </div>
          <div className="rounded-2xl border border-slate-100 bg-white p-6 shadow-md dark:border-slate-800 dark:bg-slate-900/80">
            <div>
              <h3 className="text-sm font-semibold text-slate-900 dark:text-white">
                Pipeline status
              </h3>
              <p className="text-xs text-slate-500 dark:text-slate-400">
                Current stage distribution
              </p>
            </div>
            <div className="mt-6 space-y-4">
              {demoSummary.status_funnel.map((item) => (
                <div key={item.label}>
                  <div className="flex items-center justify-between text-xs text-slate-600 dark:text-slate-300">
                    <span>{item.label}</span>
                    <span>{item.value}</span>
                  </div>
                  <div className="mt-2 h-2 rounded-full bg-slate-100 dark:bg-slate-800">
                    <div
                      className="h-2 rounded-full bg-indigo-500"
                      style={{ width: `${(item.value / maxStatusValue) * 100}%` }}
                    />
                  </div>
                </div>
              ))}
            </div>
            <div className="mt-6 rounded-2xl border border-indigo-100 bg-indigo-50 p-4 text-xs text-indigo-700 dark:border-indigo-500/30 dark:bg-indigo-500/10 dark:text-indigo-200">
              Read-only demo. Connect your inbox to unlock automation.
            </div>
          </div>
        </div>

        <div className="grid gap-6 lg:grid-cols-[1.2fr_0.8fr]">
          <div className="rounded-2xl border border-slate-100 bg-white p-6 shadow-md dark:border-slate-800 dark:bg-slate-900/80">
            <div className="flex items-center justify-between">
              <div>
                <h3 className="text-sm font-semibold text-slate-900 dark:text-white">Sample leads</h3>
                <p className="text-xs text-slate-500 dark:text-slate-400">
                  Preview of lead scoring and routing
                </p>
              </div>
              <Badge variant="info">Read-only</Badge>
            </div>
            <div className="mt-6 space-y-4">
              {demoLeads.map((lead) => (
                <div
                  key={lead.id}
                  className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-slate-100 bg-slate-50 p-4 text-sm text-slate-600 dark:border-slate-800 dark:bg-slate-950/60 dark:text-slate-300"
                >
                  <div>
                    <p className="font-semibold text-slate-900 dark:text-white">{lead.name}</p>
                    <p className="text-xs text-slate-500 dark:text-slate-400">{lead.email}</p>
                    <p className="mt-2 text-xs text-slate-500 dark:text-slate-400">{lead.summary}</p>
                  </div>
                  <div className="text-right">
                    <StatusBadge status={lead.status} />
                    <p className="mt-2 text-xs text-slate-500 dark:text-slate-400">
                      Score {lead.score}
                    </p>
                  </div>
                </div>
              ))}
            </div>
          </div>
          <div className="rounded-2xl border border-slate-100 bg-white p-6 shadow-md dark:border-slate-800 dark:bg-slate-900/80">
            <div className="flex items-center justify-between">
              <div>
                <h3 className="text-sm font-semibold text-slate-900 dark:text-white">Inbox preview</h3>
                <p className="text-xs text-slate-500 dark:text-slate-400">
                  AI-labeled inbound emails
                </p>
              </div>
              <Badge variant="info">Read-only</Badge>
            </div>
            <div className="mt-6 space-y-4">
              {demoEmails.map((email) => (
                <div
                  key={email.id}
                  className="rounded-2xl border border-slate-100 bg-slate-50 p-4 text-sm text-slate-600 dark:border-slate-800 dark:bg-slate-950/60 dark:text-slate-300"
                >
                  <div className="flex items-center justify-between">
                    <p className="font-semibold text-slate-900 dark:text-white">{email.subject}</p>
                    <StatusBadge status={email.status} label={email.status} />
                  </div>
                  <p className="mt-1 text-xs text-slate-500 dark:text-slate-400">From {email.from}</p>
                  <div className="mt-3 flex items-center gap-2">
                    <Badge>{email.category}</Badge>
                    <span className="text-xs text-slate-400 dark:text-slate-500">
                      {new Date(email.received_at).toLocaleDateString()}
                    </span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        <div className="grid gap-6 lg:grid-cols-[1.1fr_0.9fr]">
          <div className="rounded-2xl border border-slate-100 bg-white p-6 shadow-md dark:border-slate-800 dark:bg-slate-900/80">
            <div>
              <h3 className="text-sm font-semibold text-slate-900 dark:text-white">Email mix</h3>
              <p className="text-xs text-slate-500 dark:text-slate-400">
                Categories auto-detected by AI
              </p>
            </div>
            <div className="mt-6 h-56">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={demoSummary.email_category_breakdown}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" />
                  <XAxis dataKey="category" tick={{ fill: "#94a3b8", fontSize: 12 }} />
                  <YAxis tick={{ fill: "#94a3b8", fontSize: 12 }} />
                  <Tooltip
                    contentStyle={{
                      borderRadius: 12,
                      borderColor: "#e2e8f0",
                      fontSize: 12,
                    }}
                  />
                  <Bar dataKey="count" fill="#6366f1" radius={[6, 6, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            </div>
          </div>
          <div className="rounded-2xl border border-slate-100 bg-white p-6 shadow-md dark:border-slate-800 dark:bg-slate-900/80">
            <div className="flex items-center gap-2">
              <SparklesIcon className="h-5 w-5 text-indigo-500" />
              <h3 className="text-sm font-semibold text-slate-900 dark:text-white">
                Recent activity
              </h3>
            </div>
            <div className="mt-6 space-y-4">
              {demoActivities.map((activity) => (
                <div key={activity.id} className="rounded-2xl border border-slate-100 bg-slate-50 p-4 dark:border-slate-800 dark:bg-slate-950/60">
                  <p className="text-sm font-semibold text-slate-900 dark:text-white">
                    {activity.title}
                  </p>
                  <p className="mt-1 text-xs text-slate-500 dark:text-slate-400">
                    {activity.description}
                  </p>
                  <p className="mt-2 text-xs text-slate-400 dark:text-slate-500">{activity.time}</p>
                </div>
              ))}
            </div>
            <div className="mt-6 rounded-2xl border border-slate-200 bg-slate-50 p-4 text-xs text-slate-500 dark:border-slate-800 dark:bg-slate-950/60 dark:text-slate-400">
              Connect your inbox to see live automation in real time.
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Demo;
